### ISSUE TITLE
I think the necessary documents are missing

### ISSUE THREAD

**Issue by twrjie** [YaooXu/GoG#1]
After running the gog.py file, it shows that the data/cwq/data_with_ct_yx1000_-1_1.json file is missing, can you provide this file?.

**Comment by YaooXu** [comment]
I have updated readme and uploaded processed data.

**Comment by twrjie** [comment]
Firstly, thanks for answering my question last time and uploading the new data, I'm actually new to this and now I'm running the file generate_samples_with_crucial_edges.py and I'm getting an error at line 250 results = sparql.query().convert() HTTP Error 502: Bad Gateway, but I can access the site http://210.75.240.139:18890/sparql and I would like to know what the problem is.
<img width="804" alt="Snipaste_2024-05-24_16-55-50" src="https://github.com/YaooXu/GoG/assets/122782502/5b444f01-9168-456a-898d-a2c63f064c0b">

**Comment by YaooXu** [comment]
You should deploy the virtuoso service first and replace the "http://210.75.240.139:18890/sparql" with your service url, like http://127.0.0.1:8890/sparql.

**Comment by twrjie** [comment]
Thanks again for taking the trouble to reply to my question, after I downloaded virtuoso, changed the address to http://127.0.0.1:8890/sparql, and after running the generate_samples_with_crucial_edges.py it appeared list index out of range
<img width="375" alt="Snipaste_2024-05-25_16-02-12" src="https://github.com/YaooXu/GoG/assets/122782502/9f0509e4-bf35-42b3-9755-12399db86d54">

**Comment by YaooXu** [comment]
Make sure that you have deployed virtuoso correctly, see https://github.com/YaooXu/GoG/blob/main/Freebase/README.md.
