### ISSUE TITLE
Time used in freebase setup

### ISSUE THREAD

**Issue by Fangfeng205** [YaooXu/GoG#2]
I wonder how long it took you to import the cleaned data to virtuoso.If it's too long, can I turn off the computer in the middle of the way, I don't understand these details well and I haven't found a tutorial on the Internet, I would appreciate it if you could give me an answer

**Comment by YaooXu** [comment]
About 3 or 4 hours on our machine, it depends on your machine CPU. 

BTW, the default port in virtuoso is 1111, I have updated the [readme](https://github.com/GasolSun36/ToG/blob/934064c4a8a391c7f351339676f29ed764e40054/Freebase/README.md?plain=1#L31C1-L31C44.).

**Comment by Fangfeng205** [comment]
Recently I am studying the direction of knowledge enhancement LLM reasoning, and after reading your paper, I am ready to practice related code, thank you for your immediate reply

**Comment by Fangfeng205** [comment]
I imported the 125G size Filterfreebase into virtuoso, and since I imported it locally, how big will the virtuoso.db file get in the end?

**Comment by YaooXu** [comment]
About 39GB.

**Comment by Fangfeng205** [comment]
I saw in a tutorial that it took 6 days (https://www.zhuzongkui.top/virtuoso/ which seems too long) to import Filterfreebase to virsuoto, and my CPU was as follows (when I imported, the file grew by 3GB in about an hour virsuoto.db and I wanted to ask if you were using a PC.
![@} A}L8V3{R1FLHTS$% F9G](https://github.com/YaooXu/GoG/assets/130035768/bcc079da-a081-428d-935b-56d8f5065fd0)

**Comment by YaooXu** [comment]
No, I used an ubuntu server.
