### ISSUE TITLE
I want to know the results about python_example.py

### ISSUE THREAD

**Issue by youngsasa2021** [YaooXu/GoG#3]
I get the results:{'head': {'link': [], 'vars': ['name3']}, 'results': {'distinct': False, 'ordered': True, 'bindings': []}}.
I found bindings:[],is it correct?How should I do?And I want to know if I can run the whole code in my laboratory server(4090*2)?
Looking foward to your acvice!

**Comment by YaooXu** [comment]
There is something wrong in your virtuoso service, expected output is 
```bash
{'head': {'link': [], 'vars': ['name3']}, 'results': {'distinct': False, 'ordered': True, 'bindings': [{'name3': {'type': 'literal', 'xml:lang': 'en', 'value': 'Jeffrey Probst'}}, {'name3': {'type': 'literal', 'xml:lang': 'en', 'value': 'Shelly Wright'}}, {'name3': {'type': 'literal', 'xml:lang': 'en', 'value': 'Lisa Ann Russell'}}]}}
```
The size of "virtuoso.db" should be about 39GB.

**Comment by youngsasa2021** [comment]
i want to confirm it's because of
 "ld_dir('.', 'FilterFreebase', 'http://freebase.com'); 
rdf_loader_run(); "
these two codes?I need to wait for some time to generate virtuoso.db(39G,but i have only 66M)?
thank you for your advice.This is my first-time learning this database,so I'm a little confused.

**Comment by YaooXu** [comment]
`rdf_loader_run()` will take several hours (recommand running it in tmux or screen), and the size of "FilterFreebase" is about 125G.

**Comment by youngsasa2021** [comment]
yes, my filterfreebase is 125G. well，i start to wait for some time.

在 2024-05-23 14:32:34，yaoyaoyao ***@***.***> 写道：


rdf_loader_run() will take several hours (recommand running it in tmux or screen), and the size of "FilterFreebase" is about 125G.

**Comment by youngsasa2021** [comment]
thanks very much

在 2024-05-23 14:32:34，yaoyaoyao ***@***.***> 写道：


rdf_loader_run() will take several hours (recommand running it in tmux or screen), and the size of "FilterFreebase" is about 125G.

**Comment by youngsasa2021** [comment]
hello I still want to ask you a question.
I have followed the code you listed again from "gunzip freebase".After I have run "rdf_loader_run();"I waited for a long time.But my virtuoso.db is still 66MB.It is illogical.
![image](https://github.com/YaooXu/GoG/assets/108064382/3ea967a7-8775-43e4-babb-d69fafaeb49d)
![image](https://github.com/YaooXu/GoG/assets/108064382/3248dac5-10e7-44a9-9e39-118d084cfd8b)
![image](https://github.com/YaooXu/GoG/assets/108064382/0a5725d7-1957-48e6-be8f-48d08359d90f)
I want to konw if I have something wrong.Please correct me!Thank you for your advice!I really don't know about the virtuoso database.

**Comment by YaooXu** [comment]
Try to move the `FilterFreebase` into `virtuoso_opensource/database` and re-run.

**Comment by youngsasa2021** [comment]
I followed your advice and re-run these codes.Nothing has changed even tough it's been a while.
![image](https://github.com/YaooXu/GoG/assets/108064382/efd91a8a-6541-420f-b564-098bd950f129)

**Comment by YaooXu** [comment]
How long does "rdf_loader_run" takes, it should take several hours.

**Comment by youngsasa2021** [comment]
It seems to have been executed immediately.You can see this screeshot which is my code record.
![image](https://github.com/YaooXu/GoG/assets/108064382/0e3886a9-d207-4264-a188-c8050ad868c4)
Before I run "rdf_loader_run();" the database is 66MB,After I run this code ,It stiil be 66MB althogh I wailt for a long time.And I have remove the FilterFreebase as you remind me.What else could be the cause?

**Comment by youngsasa2021** [comment]
Now I'm trying to execute "ld_dir('{completed path}', 'FilterFreebase', 'http://freebase.com');",and i find that it seems running all the time.And it don't reply my "done".Although my "virtuoso.db" is still 66MB.Maybe before I havn't executed correctedly.Thank you for your help!   I 'll trace this result.
![image](https://github.com/YaooXu/GoG/assets/108064382/182746e9-e611-4142-8bbe-ebaa34f1b99b)

**Comment by youngsasa2021** [comment]
hello,thanks for your advice.I have installed Freebase and get correct results for test_example,py.But I still want to ask for code for run_llm. When I run GOG through my lab server,I found connection error.I have bought api_key and set base_url.

**Comment by YaooXu** [comment]
I suggest that you should test your api_key and network in a simple test file to make sure you can access openai correctly. You might need VPN to access openai api.

**Comment by youngsasa2021** [comment]
I want to know the reasons why my exact match result is just 29.1%.
![image](https://github.com/YaooXu/GoG/assets/108064382/07548b4a-2aeb-47e9-9f43-bd06bba827a7)
how could I get better result except using GPT-4?

**Comment by YaooXu** [comment]
That's weird, do you use the offical openai api？

**Comment by youngsasa2021** [comment]
Actually I have use openai key purchased through Taobao. Will this have any effect on the exact matching result?

**Comment by YaooXu** [comment]
These websites are unreliable, as they might not use the real gpt-3.5, and I suggest you use Qwen-1.5-72b-chat if you have trouble using openai api. You can use Qwen-1.5-72b-chat by deploying it with vLLM or from https://cloud.infini-ai.com/login?redirect=/genstudio/model

**Comment by youngsasa2021** [comment]
thank you for your advice.I will try it.

**Comment by Lin-zj666** [comment]
@youngsasa2021 Hello, I'm facing the same issue. Could you please share how you resolved it? Did you change "ld_dir('.', 'FilterFreebase', 'http://freebase.com/');" to "ld_dir('{completed path}', 'FilterFreebase', 'http://freebase.com/);"? However, after making this modification, it seems the issue persists. Your response would be greatly appreciated!

**Comment by youngsasa2021** [comment]
hello, I tried many times.I used the same codes  at last successfully. You should make sure that  you have move filterfreebase to the database and follow the codes.

在 2024-07-10 18:02:47，Lin-zj666 ***@***.***> 写道：


@youngsasa2021 Hello, I'm facing the same issue. Could you please share how you resolved it? Did you change "ld_dir('.', 'FilterFreebase', 'http://freebase.com/');" to "ld_dir('{completed path}', 'FilterFreebase', 'http://freebase.com/);"? However, after making this modification, it seems the issue persists. Your response would be greatly appreciated!

**Comment by youngsasa2021** [comment]
you can try another time as same as author

在 2024-07-10 20:58:16，"杨茗然" ***@***.***> 写道：
hello, I tried many times.I used the same codes  at last successfully. You should make sure that  you have move filterfreebase to the database and follow the codes.

在 2024-07-10 18:02:47，Lin-zj666 ***@***.***> 写道：


@youngsasa2021 Hello, I'm facing the same issue. Could you please share how you resolved it? Did you change "ld_dir('.', 'FilterFreebase', 'http://freebase.com/');" to "ld_dir('{completed path}', 'FilterFreebase', 'http://freebase.com/);"? However, after making this modification, it seems the issue persists. Your response would be greatly appreciated!

**Comment by Lin-zj666** [comment]
Okay, thank you for your help. I have successfully resolved the issue.
