### ISSUE TITLE
log文件

### ISSUE THREAD

**Issue by JuanLi1621** [YaooXu/GoG#6]
你好，请问可以提供一个数据集结果的log文件吗或者10多个问题的也行，比如webqsp/data_with_ct_1000_-1_1.json这个数据对应results的log文件，我们想参照中间的结果看看，谢谢啦

**Comment by YaooXu** [comment]
See prob_results/cwq/gpt-3.5-turbo-0613/10_3_0.7_data_with_ct_0.2_predictions.json
