### ISSUE TITLE
Filtering additional Wikidata

### ISSUE THREAD

**Issue by MINJIK01** [YaooXu/GoG#8]
Thank you for your excellent work.

While implementing your code, I had a question regarding whether I need to filter Wikidata for mapping like Freebase.

Could I get some clarification on this?

**Comment by YaooXu** [comment]
We didn't conduct experiments on Wikidata, so you don't have to preprocess Wikidata.

**Comment by MINJIK01** [comment]
Sorry, I think my question was unclear. I was referring to the section on implementing the Freebase process, specifically the part about mapping data to Wikidata.

https://github.com/YaooXu/GoG/tree/main/Freebase#mapping-data-to-wikidata

"""
Mapping data to Wikidata
Due to the partial incompleteness of the data present in the freebase dump, we need to map some of the entities with missing partial relationships to wikidata. We download these rdf data via this public [link](https://developers.google.com/freebase?hl=en#freebase-wikidata-mappings)

we can use the above method to add it into virtuoso.
"""

Sorry for the confusion..!

**Comment by YaooXu** [comment]
ToG also did this, so I suggest you do this.

**Comment by MINJIK01** [comment]
Thank you for answering!
