### ISSUE TITLE
GoG/prompts_v2/examples_no-kg is exactly same as GoG/prompts_v2/examples

### ISSUE THREAD

**Issue by wusw14** [YaooXu/GoG#9]
Hi,

Thanks for sharing. I found out that the prompt templates used for the setting with and without using KG are the same. Is the file "GoG/prompts_v2/examples_no-kg" uploaded correctly?

**Comment by YaooXu** [comment]
https://github.com/YaooXu/GoG/blob/c0b2c362ed77c5eb98290071f5362b2f3a546c6e/src/GoG.py#L40

In this function, you can find that we make the LLM output the whole process directly without interacting with KG.  In this case, LLM will output "think", "action" and "observation" itself, so  the "GoG/prompts_v2/examples_no-kg" is the same with the "GoG/prompts_v2/examples". 

The reason why we have two duplicated files is that we want to  make the output directories different. Sorry for the confusion.

**Comment by wusw14** [comment]
Thanks for your reply. According to the illustrations in the paper, the search action should (based on my understanding) not be available if LLM is only allowed to generate by itself. It seems to be not that reasonable to use the same prompt for the setting without KG.

**Comment by YaooXu** [comment]
In experiments without KG, although the LLM performs a search operation, it does not actually retrieve information from the KB. Instead, the subsequent observations are entirely generated by the LLM itself. This process can also be understood as a form of Chain of Thought (CoT).
